name: KiCad

on: [push, pull_request, workflow_dispatch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build outputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install KiCad 9.0
        run: |
          sudo add-apt-repository ppa:kicad/kicad-9.0-releases
          sudo apt update
          sudo apt-get install --no-install-recommends kicad kicad-footprints kicad-symbols
      - name: Set up KiCad libraries
        run: |
          mkdir -p ~/.config/kicad/9.0
          cp .github/kicad-config/* ~/.config/kicad/9.0
      - name: Make
        run: make
      - name: Upload artifact
        # run even if 'make' failed
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ADF4158_PCB-outputs
          path: outputs
      - name: Upload GH pages artifact
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: outputs      
  deploy-gh-pages:
    name: Deploy to GH Pages
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
